# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_module', models.CharField(max_length=200)),
                ('status', models.CharField(default='skipped', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=200)),
                ('date_run', models.DateTimeField(default=datetime.datetime(2017, 6, 30, 2, 48, 2, 33785))),
                ('num_tests', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.TestSuite'),
        ),
    ]
