# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20170630_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuite',
            old_name='failed',
            new_name='num_failed',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='passed',
            new_name='num_passed',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='skipped',
            new_name='num_skipped',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_suite',
            field=models.CharField(max_length=200),
        ),
    ]
