# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20170705_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='date_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
