# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_testcase_date_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_name',
            field=models.CharField(max_length=200),
        ),
    ]
