# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20170711_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='failing_context',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='system',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
