# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20170930_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='test_suite',
            new_name='suite_name',
        ),
    ]
