# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20171109_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='test_bench',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='system',
            field=models.CharField(default='', max_length=200),
        ),
    ]
