# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0012_auto_20171110_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='failing_context',
            field=models.CharField(default='NA', max_length=900),
        ),
    ]
